/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'email' : [] | [string],
  'website' : [] | [string],
  'phone' : [] | [string],
}
export interface CreateDonationInput {
  'cancelUrl' : string,
  'currency' : string,
  'templeId' : TempleId,
  'amount' : bigint,
  'successUrl' : string,
}
export interface DarshanTiming {
  'closeTime' : string,
  'timingLabel' : string,
  'breakStart' : [] | [string],
  'breakEnd' : [] | [string],
  'openTime' : string,
}
export interface DonationCheckoutResult {
  'donationId' : DonationId,
  'checkoutUrl' : string,
  'sessionId' : string,
}
export type DonationId = bigint;
export interface DonationOption {
  'donationType' : string,
  'description' : string,
  'amount' : bigint,
}
export interface DonationRecord {
  'id' : DonationId,
  'status' : DonationStatus,
  'createdAt' : Timestamp,
  'templeName' : string,
  'updatedAt' : Timestamp,
  'currency' : string,
  'templeId' : TempleId,
  'stripeSessionId' : string,
  'amount' : bigint,
  'donor' : UserId,
}
export interface DonationStats {
  'pendingCount' : bigint,
  'completedCount' : bigint,
  'templeName' : string,
  'totalAmount' : bigint,
  'templeId' : TempleId,
  'totalDonations' : bigint,
}
export type DonationStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface Faq {
  'id' : FaqId,
  'question' : string,
  'createdAt' : Timestamp,
  'answer' : string,
  'updatedAt' : Timestamp,
  'templeId' : TempleId,
}
export type FaqId = bigint;
export interface FaqInput {
  'question' : string,
  'answer' : string,
  'templeId' : TempleId,
}
export interface Festival {
  'date' : string,
  'name' : string,
  'significance' : string,
}
export interface PaginatedResult {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<TempleSummary>,
}
export interface PaginationParams { 'offset' : bigint, 'limit' : bigint }
export interface Pooja {
  'name' : string,
  'time' : string,
  'description' : string,
  'price' : [] | [bigint],
  'isIncluded' : boolean,
}
export interface Review {
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : string,
  'templeId' : TempleId,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ReviewInput {
  'comment' : string,
  'templeId' : TempleId,
  'rating' : bigint,
}
export interface SearchParams {
  'cityFilter' : [] | [string],
  'pagination' : PaginationParams,
  'searchTerm' : string,
  'stateFilter' : [] | [string],
}
export interface SpecialDarshan {
  'name' : string,
  'description' : string,
  'availableDays' : Array<string>,
  'price' : bigint,
}
export interface Temple {
  'id' : TempleId,
  'poojaSchedule' : Array<Pooja>,
  'contactInfo' : ContactInfo,
  'nonHinduRestriction' : boolean,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'architectureStyle' : string,
  'description' : string,
  'history' : string,
  'district' : string,
  'donationOptions' : Array<DonationOption>,
  'updatedAt' : Timestamp,
  'state' : string,
  'averageVisitDuration' : bigint,
  'address' : string,
  'specialDarshans' : Array<SpecialDarshan>,
  'festivalCalendar' : Array<Festival>,
  'deity' : string,
  'darshanTimings' : Array<DarshanTiming>,
  'images' : Array<string>,
}
export type TempleId = bigint;
export interface TempleInput {
  'poojaSchedule' : Array<Pooja>,
  'contactInfo' : ContactInfo,
  'nonHinduRestriction' : boolean,
  'city' : string,
  'name' : string,
  'tags' : Array<string>,
  'architectureStyle' : string,
  'description' : string,
  'history' : string,
  'district' : string,
  'donationOptions' : Array<DonationOption>,
  'state' : string,
  'averageVisitDuration' : bigint,
  'address' : string,
  'specialDarshans' : Array<SpecialDarshan>,
  'festivalCalendar' : Array<Festival>,
  'deity' : string,
  'darshanTimings' : Array<DarshanTiming>,
  'images' : Array<string>,
}
export interface TempleSummary {
  'id' : TempleId,
  'nonHinduRestriction' : boolean,
  'city' : string,
  'name' : string,
  'tags' : Array<string>,
  'architectureStyle' : string,
  'district' : string,
  'state' : string,
  'averageVisitDuration' : bigint,
  'address' : string,
  'deity' : string,
  'images' : Array<string>,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'visitHistory' : Array<TempleId>,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'bookmarkedTemples' : Array<TempleId>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addFAQ' : ActorMethod<[FaqInput], Faq>,
  'addReview' : ActorMethod<[ReviewInput], Review>,
  'addTemple' : ActorMethod<[TempleInput], Temple>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bookmarkTemple' : ActorMethod<[TempleId], boolean>,
  'createCheckoutSession' : ActorMethod<
    [CreateDonationInput],
    DonationCheckoutResult
  >,
  'deleteFAQ' : ActorMethod<[FaqId], boolean>,
  'deleteTemple' : ActorMethod<[TempleId], boolean>,
  'getAllDonationStats' : ActorMethod<[], Array<DonationStats>>,
  'getAllTemples' : ActorMethod<[], Array<Temple>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDonationStats' : ActorMethod<[TempleId], DonationStats>,
  'getDonationsByTemple' : ActorMethod<[TempleId], Array<DonationRecord>>,
  'getFAQs' : ActorMethod<[TempleId], Array<Faq>>,
  'getReviews' : ActorMethod<[TempleId], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], boolean>,
  'getTemple' : ActorMethod<[TempleId], [] | [Temple]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<UserSummary>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeBookmark' : ActorMethod<[TempleId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTemples' : ActorMethod<[SearchParams], PaginatedResult>,
  'setStripeConfiguration' : ActorMethod<[string, Array<string>], undefined>,
  'setUserRole' : ActorMethod<[UserId, UserRole], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateFAQ' : ActorMethod<[FaqId, FaqInput], [] | [Faq]>,
  'updateTemple' : ActorMethod<[TempleId, TempleInput], [] | [Temple]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];