/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TempleId = IDL.Nat;
export const FaqInput = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'templeId' : TempleId,
});
export const FaqId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Faq = IDL.Record({
  'id' : FaqId,
  'question' : IDL.Text,
  'createdAt' : Timestamp,
  'answer' : IDL.Text,
  'updatedAt' : Timestamp,
  'templeId' : TempleId,
});
export const ReviewInput = IDL.Record({
  'comment' : IDL.Text,
  'templeId' : TempleId,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const UserId = IDL.Principal;
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'templeId' : TempleId,
  'rating' : IDL.Nat,
});
export const Pooja = IDL.Record({
  'name' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
  'isIncluded' : IDL.Bool,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const DonationOption = IDL.Record({
  'donationType' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SpecialDarshan = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'availableDays' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const Festival = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'significance' : IDL.Text,
});
export const DarshanTiming = IDL.Record({
  'closeTime' : IDL.Text,
  'timingLabel' : IDL.Text,
  'breakStart' : IDL.Opt(IDL.Text),
  'breakEnd' : IDL.Opt(IDL.Text),
  'openTime' : IDL.Text,
});
export const TempleInput = IDL.Record({
  'poojaSchedule' : IDL.Vec(Pooja),
  'contactInfo' : ContactInfo,
  'nonHinduRestriction' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'architectureStyle' : IDL.Text,
  'description' : IDL.Text,
  'history' : IDL.Text,
  'district' : IDL.Text,
  'donationOptions' : IDL.Vec(DonationOption),
  'state' : IDL.Text,
  'averageVisitDuration' : IDL.Nat,
  'address' : IDL.Text,
  'specialDarshans' : IDL.Vec(SpecialDarshan),
  'festivalCalendar' : IDL.Vec(Festival),
  'deity' : IDL.Text,
  'darshanTimings' : IDL.Vec(DarshanTiming),
  'images' : IDL.Vec(IDL.Text),
});
export const Temple = IDL.Record({
  'id' : TempleId,
  'poojaSchedule' : IDL.Vec(Pooja),
  'contactInfo' : ContactInfo,
  'nonHinduRestriction' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'architectureStyle' : IDL.Text,
  'description' : IDL.Text,
  'history' : IDL.Text,
  'district' : IDL.Text,
  'donationOptions' : IDL.Vec(DonationOption),
  'updatedAt' : Timestamp,
  'state' : IDL.Text,
  'averageVisitDuration' : IDL.Nat,
  'address' : IDL.Text,
  'specialDarshans' : IDL.Vec(SpecialDarshan),
  'festivalCalendar' : IDL.Vec(Festival),
  'deity' : IDL.Text,
  'darshanTimings' : IDL.Vec(DarshanTiming),
  'images' : IDL.Vec(IDL.Text),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateDonationInput = IDL.Record({
  'cancelUrl' : IDL.Text,
  'currency' : IDL.Text,
  'templeId' : TempleId,
  'amount' : IDL.Nat,
  'successUrl' : IDL.Text,
});
export const DonationId = IDL.Nat;
export const DonationCheckoutResult = IDL.Record({
  'donationId' : DonationId,
  'checkoutUrl' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const DonationStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'completedCount' : IDL.Nat,
  'templeName' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'templeId' : TempleId,
  'totalDonations' : IDL.Nat,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfile = IDL.Record({
  'visitHistory' : IDL.Vec(TempleId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'bookmarkedTemples' : IDL.Vec(TempleId),
});
export const DonationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const DonationRecord = IDL.Record({
  'id' : DonationId,
  'status' : DonationStatus,
  'createdAt' : Timestamp,
  'templeName' : IDL.Text,
  'updatedAt' : Timestamp,
  'currency' : IDL.Text,
  'templeId' : TempleId,
  'stripeSessionId' : IDL.Text,
  'amount' : IDL.Nat,
  'donor' : UserId,
});
export const UserSummary = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const PaginationParams = IDL.Record({
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
});
export const SearchParams = IDL.Record({
  'cityFilter' : IDL.Opt(IDL.Text),
  'pagination' : PaginationParams,
  'searchTerm' : IDL.Text,
  'stateFilter' : IDL.Opt(IDL.Text),
});
export const TempleSummary = IDL.Record({
  'id' : TempleId,
  'nonHinduRestriction' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'architectureStyle' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'averageVisitDuration' : IDL.Nat,
  'address' : IDL.Text,
  'deity' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const PaginatedResult = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(TempleSummary),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addFAQ' : IDL.Func([FaqInput], [Faq], []),
  'addReview' : IDL.Func([ReviewInput], [Review], []),
  'addTemple' : IDL.Func([TempleInput], [Temple], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bookmarkTemple' : IDL.Func([TempleId], [IDL.Bool], []),
  'createCheckoutSession' : IDL.Func(
      [CreateDonationInput],
      [DonationCheckoutResult],
      [],
    ),
  'deleteFAQ' : IDL.Func([FaqId], [IDL.Bool], []),
  'deleteTemple' : IDL.Func([TempleId], [IDL.Bool], []),
  'getAllDonationStats' : IDL.Func([], [IDL.Vec(DonationStats)], ['query']),
  'getAllTemples' : IDL.Func([], [IDL.Vec(Temple)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDonationStats' : IDL.Func([TempleId], [DonationStats], ['query']),
  'getDonationsByTemple' : IDL.Func(
      [TempleId],
      [IDL.Vec(DonationRecord)],
      ['query'],
    ),
  'getFAQs' : IDL.Func([TempleId], [IDL.Vec(Faq)], ['query']),
  'getReviews' : IDL.Func([TempleId], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getTemple' : IDL.Func([TempleId], [IDL.Opt(Temple)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([TempleId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTemples' : IDL.Func([SearchParams], [PaginatedResult], ['query']),
  'setStripeConfiguration' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'setUserRole' : IDL.Func([UserId, UserRole], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFAQ' : IDL.Func([FaqId, FaqInput], [IDL.Opt(Faq)], []),
  'updateTemple' : IDL.Func([TempleId, TempleInput], [IDL.Opt(Temple)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TempleId = IDL.Nat;
  const FaqInput = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'templeId' : TempleId,
  });
  const FaqId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Faq = IDL.Record({
    'id' : FaqId,
    'question' : IDL.Text,
    'createdAt' : Timestamp,
    'answer' : IDL.Text,
    'updatedAt' : Timestamp,
    'templeId' : TempleId,
  });
  const ReviewInput = IDL.Record({
    'comment' : IDL.Text,
    'templeId' : TempleId,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const UserId = IDL.Principal;
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'templeId' : TempleId,
    'rating' : IDL.Nat,
  });
  const Pooja = IDL.Record({
    'name' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
    'isIncluded' : IDL.Bool,
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const DonationOption = IDL.Record({
    'donationType' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SpecialDarshan = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'availableDays' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const Festival = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'significance' : IDL.Text,
  });
  const DarshanTiming = IDL.Record({
    'closeTime' : IDL.Text,
    'timingLabel' : IDL.Text,
    'breakStart' : IDL.Opt(IDL.Text),
    'breakEnd' : IDL.Opt(IDL.Text),
    'openTime' : IDL.Text,
  });
  const TempleInput = IDL.Record({
    'poojaSchedule' : IDL.Vec(Pooja),
    'contactInfo' : ContactInfo,
    'nonHinduRestriction' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'architectureStyle' : IDL.Text,
    'description' : IDL.Text,
    'history' : IDL.Text,
    'district' : IDL.Text,
    'donationOptions' : IDL.Vec(DonationOption),
    'state' : IDL.Text,
    'averageVisitDuration' : IDL.Nat,
    'address' : IDL.Text,
    'specialDarshans' : IDL.Vec(SpecialDarshan),
    'festivalCalendar' : IDL.Vec(Festival),
    'deity' : IDL.Text,
    'darshanTimings' : IDL.Vec(DarshanTiming),
    'images' : IDL.Vec(IDL.Text),
  });
  const Temple = IDL.Record({
    'id' : TempleId,
    'poojaSchedule' : IDL.Vec(Pooja),
    'contactInfo' : ContactInfo,
    'nonHinduRestriction' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'architectureStyle' : IDL.Text,
    'description' : IDL.Text,
    'history' : IDL.Text,
    'district' : IDL.Text,
    'donationOptions' : IDL.Vec(DonationOption),
    'updatedAt' : Timestamp,
    'state' : IDL.Text,
    'averageVisitDuration' : IDL.Nat,
    'address' : IDL.Text,
    'specialDarshans' : IDL.Vec(SpecialDarshan),
    'festivalCalendar' : IDL.Vec(Festival),
    'deity' : IDL.Text,
    'darshanTimings' : IDL.Vec(DarshanTiming),
    'images' : IDL.Vec(IDL.Text),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateDonationInput = IDL.Record({
    'cancelUrl' : IDL.Text,
    'currency' : IDL.Text,
    'templeId' : TempleId,
    'amount' : IDL.Nat,
    'successUrl' : IDL.Text,
  });
  const DonationId = IDL.Nat;
  const DonationCheckoutResult = IDL.Record({
    'donationId' : DonationId,
    'checkoutUrl' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const DonationStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'completedCount' : IDL.Nat,
    'templeName' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'templeId' : TempleId,
    'totalDonations' : IDL.Nat,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfile = IDL.Record({
    'visitHistory' : IDL.Vec(TempleId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'bookmarkedTemples' : IDL.Vec(TempleId),
  });
  const DonationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const DonationRecord = IDL.Record({
    'id' : DonationId,
    'status' : DonationStatus,
    'createdAt' : Timestamp,
    'templeName' : IDL.Text,
    'updatedAt' : Timestamp,
    'currency' : IDL.Text,
    'templeId' : TempleId,
    'stripeSessionId' : IDL.Text,
    'amount' : IDL.Nat,
    'donor' : UserId,
  });
  const UserSummary = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const PaginationParams = IDL.Record({
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
  });
  const SearchParams = IDL.Record({
    'cityFilter' : IDL.Opt(IDL.Text),
    'pagination' : PaginationParams,
    'searchTerm' : IDL.Text,
    'stateFilter' : IDL.Opt(IDL.Text),
  });
  const TempleSummary = IDL.Record({
    'id' : TempleId,
    'nonHinduRestriction' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'architectureStyle' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'averageVisitDuration' : IDL.Nat,
    'address' : IDL.Text,
    'deity' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const PaginatedResult = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(TempleSummary),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addFAQ' : IDL.Func([FaqInput], [Faq], []),
    'addReview' : IDL.Func([ReviewInput], [Review], []),
    'addTemple' : IDL.Func([TempleInput], [Temple], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bookmarkTemple' : IDL.Func([TempleId], [IDL.Bool], []),
    'createCheckoutSession' : IDL.Func(
        [CreateDonationInput],
        [DonationCheckoutResult],
        [],
      ),
    'deleteFAQ' : IDL.Func([FaqId], [IDL.Bool], []),
    'deleteTemple' : IDL.Func([TempleId], [IDL.Bool], []),
    'getAllDonationStats' : IDL.Func([], [IDL.Vec(DonationStats)], ['query']),
    'getAllTemples' : IDL.Func([], [IDL.Vec(Temple)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDonationStats' : IDL.Func([TempleId], [DonationStats], ['query']),
    'getDonationsByTemple' : IDL.Func(
        [TempleId],
        [IDL.Vec(DonationRecord)],
        ['query'],
      ),
    'getFAQs' : IDL.Func([TempleId], [IDL.Vec(Faq)], ['query']),
    'getReviews' : IDL.Func([TempleId], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getTemple' : IDL.Func([TempleId], [IDL.Opt(Temple)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([TempleId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTemples' : IDL.Func([SearchParams], [PaginatedResult], ['query']),
    'setStripeConfiguration' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'setUserRole' : IDL.Func([UserId, UserRole], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFAQ' : IDL.Func([FaqId, FaqInput], [IDL.Opt(Faq)], []),
    'updateTemple' : IDL.Func([TempleId, TempleInput], [IDL.Opt(Temple)], []),
  });
};

export const init = ({ IDL }) => { return []; };