/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FaqInput {
    question: string;
    answer: string;
    templeId: TempleId;
}
export interface SearchParams {
    cityFilter?: string;
    pagination: PaginationParams;
    searchTerm: string;
    stateFilter?: string;
}
export interface UserSummary {
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Pooja {
    name: string;
    time: string;
    description: string;
    price?: bigint;
    isIncluded: boolean;
}
export interface PaginatedResult {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<TempleSummary>;
}
export type ReviewId = bigint;
export type FaqId = bigint;
export interface DarshanTiming {
    closeTime: string;
    timingLabel: string;
    breakStart?: string;
    breakEnd?: string;
    openTime: string;
}
export interface Review {
    id: ReviewId;
    userId: UserId;
    createdAt: Timestamp;
    comment: string;
    templeId: TempleId;
    rating: bigint;
}
export interface DonationOption {
    donationType: string;
    description: string;
    amount: bigint;
}
export interface CreateDonationInput {
    cancelUrl: string;
    currency: string;
    templeId: TempleId;
    amount: bigint;
    successUrl: string;
}
export interface TempleInput {
    poojaSchedule: Array<Pooja>;
    contactInfo: ContactInfo;
    nonHinduRestriction: boolean;
    city: string;
    name: string;
    tags: Array<string>;
    architectureStyle: string;
    description: string;
    history: string;
    district: string;
    donationOptions: Array<DonationOption>;
    state: string;
    averageVisitDuration: bigint;
    address: string;
    specialDarshans: Array<SpecialDarshan>;
    festivalCalendar: Array<Festival>;
    deity: string;
    darshanTimings: Array<DarshanTiming>;
    images: Array<string>;
}
export interface SpecialDarshan {
    name: string;
    description: string;
    availableDays: Array<string>;
    price: bigint;
}
export interface Temple {
    id: TempleId;
    poojaSchedule: Array<Pooja>;
    contactInfo: ContactInfo;
    nonHinduRestriction: boolean;
    city: string;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    architectureStyle: string;
    description: string;
    history: string;
    district: string;
    donationOptions: Array<DonationOption>;
    updatedAt: Timestamp;
    state: string;
    averageVisitDuration: bigint;
    address: string;
    specialDarshans: Array<SpecialDarshan>;
    festivalCalendar: Array<Festival>;
    deity: string;
    darshanTimings: Array<DarshanTiming>;
    images: Array<string>;
}
export interface ContactInfo {
    email?: string;
    website?: string;
    phone?: string;
}
export interface Festival {
    date: string;
    name: string;
    significance: string;
}
export interface DonationCheckoutResult {
    donationId: DonationId;
    checkoutUrl: string;
    sessionId: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PaginationParams {
    offset: bigint;
    limit: bigint;
}
export type UserId = Principal;
export interface TempleSummary {
    id: TempleId;
    nonHinduRestriction: boolean;
    city: string;
    name: string;
    tags: Array<string>;
    architectureStyle: string;
    district: string;
    state: string;
    averageVisitDuration: bigint;
    address: string;
    deity: string;
    images: Array<string>;
}
export interface Faq {
    id: FaqId;
    question: string;
    createdAt: Timestamp;
    answer: string;
    updatedAt: Timestamp;
    templeId: TempleId;
}
export interface DonationRecord {
    id: DonationId;
    status: DonationStatus;
    createdAt: Timestamp;
    templeName: string;
    updatedAt: Timestamp;
    currency: string;
    templeId: TempleId;
    stripeSessionId: string;
    amount: bigint;
    donor: UserId;
}
export interface DonationStats {
    pendingCount: bigint;
    completedCount: bigint;
    templeName: string;
    totalAmount: bigint;
    templeId: TempleId;
    totalDonations: bigint;
}
export type DonationId = bigint;
export interface ReviewInput {
    comment: string;
    templeId: TempleId;
    rating: bigint;
}
export interface UserProfile {
    visitHistory: Array<TempleId>;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    bookmarkedTemples: Array<TempleId>;
}
export type TempleId = bigint;
export enum DonationStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addFAQ(input: FaqInput): Promise<Faq>;
    addReview(input: ReviewInput): Promise<Review>;
    addTemple(input: TempleInput): Promise<Temple>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    bookmarkTemple(templeId: TempleId): Promise<boolean>;
    createCheckoutSession(input: CreateDonationInput): Promise<DonationCheckoutResult>;
    deleteFAQ(id: FaqId): Promise<boolean>;
    deleteTemple(id: TempleId): Promise<boolean>;
    getAllDonationStats(): Promise<Array<DonationStats>>;
    getAllTemples(): Promise<Array<Temple>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDonationStats(templeId: TempleId): Promise<DonationStats>;
    getDonationsByTemple(templeId: TempleId): Promise<Array<DonationRecord>>;
    getFAQs(templeId: TempleId): Promise<Array<Faq>>;
    getReviews(templeId: TempleId): Promise<Array<Review>>;
    getStripeSessionStatus(sessionId: string): Promise<boolean>;
    getTemple(id: TempleId): Promise<Temple | null>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    getUsers(): Promise<Array<UserSummary>>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    removeBookmark(templeId: TempleId): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTemples(params: SearchParams): Promise<PaginatedResult>;
    setStripeConfiguration(secretKey: string, allowedCountries: Array<string>): Promise<void>;
    setUserRole(user: UserId, role: UserRole): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateFAQ(id: FaqId, input: FaqInput): Promise<Faq | null>;
    updateTemple(id: TempleId, input: TempleInput): Promise<Temple | null>;
}
import type { ContactInfo as _ContactInfo, DarshanTiming as _DarshanTiming, DonationId as _DonationId, DonationOption as _DonationOption, DonationRecord as _DonationRecord, DonationStatus as _DonationStatus, Faq as _Faq, Festival as _Festival, PaginationParams as _PaginationParams, Pooja as _Pooja, SearchParams as _SearchParams, SpecialDarshan as _SpecialDarshan, Temple as _Temple, TempleId as _TempleId, TempleInput as _TempleInput, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserSummary as _UserSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addFAQ(arg0: FaqInput): Promise<Faq> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0);
            return result;
        }
    }
    async addReview(arg0: ReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addTemple(arg0: TempleInput): Promise<Temple> {
        if (this.processError) {
            try {
                const result = await this.actor.addTemple(to_candid_TempleInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Temple_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTemple(to_candid_TempleInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Temple_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookmarkTemple(arg0: TempleId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bookmarkTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookmarkTemple(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: CreateDonationInput): Promise<DonationCheckoutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0);
            return result;
        }
    }
    async deleteFAQ(arg0: FaqId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFAQ(arg0);
            return result;
        }
    }
    async deleteTemple(arg0: TempleId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemple(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemple(arg0);
            return result;
        }
    }
    async getAllDonationStats(): Promise<Array<DonationStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonationStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonationStats();
            return result;
        }
    }
    async getAllTemples(): Promise<Array<Temple>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTemples();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTemples();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationStats(arg0: TempleId): Promise<DonationStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationStats(arg0);
            return result;
        }
    }
    async getDonationsByTemple(arg0: TempleId): Promise<Array<DonationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsByTemple(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsByTemple(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFAQs(arg0: TempleId): Promise<Array<Faq>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQs(arg0);
            return result;
        }
    }
    async getReviews(arg0: TempleId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return result;
        }
    }
    async getTemple(arg0: TempleId): Promise<Temple | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemple(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemple(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async removeBookmark(arg0: TempleId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchTemples(arg0: SearchParams): Promise<PaginatedResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTemples(to_candid_SearchParams_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTemples(to_candid_SearchParams_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0, arg1);
            return result;
        }
    }
    async setUserRole(arg0: UserId, arg1: UserRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateFAQ(arg0: FaqId, arg1: FaqInput): Promise<Faq | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFAQ(arg0, arg1);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFAQ(arg0, arg1);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTemple(arg0: TempleId, arg1: TempleInput): Promise<Temple | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemple(arg0, to_candid_TempleInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemple(arg0, to_candid_TempleInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContactInfo_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInfo): ContactInfo {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DarshanTiming_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DarshanTiming): DarshanTiming {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DonationRecord_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationRecord): DonationRecord {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_DonationStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationStatus): DonationStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Pooja_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pooja): Pooja {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Temple_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Temple): Temple {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserSummary_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): UserSummary {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Temple]): Temple | null {
    return value.length === 0 ? null : from_candid_Temple_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Faq]): Faq | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TempleId;
    poojaSchedule: Array<_Pooja>;
    contactInfo: _ContactInfo;
    nonHinduRestriction: boolean;
    city: string;
    name: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    architectureStyle: string;
    description: string;
    history: string;
    district: string;
    donationOptions: Array<_DonationOption>;
    updatedAt: _Timestamp;
    state: string;
    averageVisitDuration: bigint;
    address: string;
    specialDarshans: Array<_SpecialDarshan>;
    festivalCalendar: Array<_Festival>;
    deity: string;
    darshanTimings: Array<_DarshanTiming>;
    images: Array<string>;
}): {
    id: TempleId;
    poojaSchedule: Array<Pooja>;
    contactInfo: ContactInfo;
    nonHinduRestriction: boolean;
    city: string;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    architectureStyle: string;
    description: string;
    history: string;
    district: string;
    donationOptions: Array<DonationOption>;
    updatedAt: Timestamp;
    state: string;
    averageVisitDuration: bigint;
    address: string;
    specialDarshans: Array<SpecialDarshan>;
    festivalCalendar: Array<Festival>;
    deity: string;
    darshanTimings: Array<DarshanTiming>;
    images: Array<string>;
} {
    return {
        id: value.id,
        poojaSchedule: from_candid_vec_n13(_uploadFile, _downloadFile, value.poojaSchedule),
        contactInfo: from_candid_ContactInfo_n17(_uploadFile, _downloadFile, value.contactInfo),
        nonHinduRestriction: value.nonHinduRestriction,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        architectureStyle: value.architectureStyle,
        description: value.description,
        history: value.history,
        district: value.district,
        donationOptions: value.donationOptions,
        updatedAt: value.updatedAt,
        state: value.state,
        averageVisitDuration: value.averageVisitDuration,
        address: value.address,
        specialDarshans: value.specialDarshans,
        festivalCalendar: value.festivalCalendar,
        deity: value.deity,
        darshanTimings: from_candid_vec_n20(_uploadFile, _downloadFile, value.darshanTimings),
        images: value.images
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    time: string;
    description: string;
    price: [] | [bigint];
    isIncluded: boolean;
}): {
    name: string;
    time: string;
    description: string;
    price?: bigint;
    isIncluded: boolean;
} {
    return {
        name: value.name,
        time: value.time,
        description: value.description,
        price: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.price)),
        isIncluded: value.isIncluded
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: [] | [string];
    website: [] | [string];
    phone: [] | [string];
}): {
    email?: string;
    website?: string;
    phone?: string;
} {
    return {
        email: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.email)),
        website: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.website)),
        phone: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closeTime: string;
    timingLabel: string;
    breakStart: [] | [string];
    breakEnd: [] | [string];
    openTime: string;
}): {
    closeTime: string;
    timingLabel: string;
    breakStart?: string;
    breakEnd?: string;
    openTime: string;
} {
    return {
        closeTime: value.closeTime,
        timingLabel: value.timingLabel,
        breakStart: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.breakStart)),
        breakEnd: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.breakEnd)),
        openTime: value.openTime
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitHistory: Array<_TempleId>;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    bookmarkedTemples: Array<_TempleId>;
}): {
    visitHistory: Array<TempleId>;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    bookmarkedTemples: Array<TempleId>;
} {
    return {
        visitHistory: value.visitHistory,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n29(_uploadFile, _downloadFile, value.role),
        email: value.email,
        bookmarkedTemples: value.bookmarkedTemples
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DonationId;
    status: _DonationStatus;
    createdAt: _Timestamp;
    templeName: string;
    updatedAt: _Timestamp;
    currency: string;
    templeId: _TempleId;
    stripeSessionId: string;
    amount: bigint;
    donor: _UserId;
}): {
    id: DonationId;
    status: DonationStatus;
    createdAt: Timestamp;
    templeName: string;
    updatedAt: Timestamp;
    currency: string;
    templeId: TempleId;
    stripeSessionId: string;
    amount: bigint;
    donor: UserId;
} {
    return {
        id: value.id,
        status: from_candid_DonationStatus_n36(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        templeName: value.templeName,
        updatedAt: value.updatedAt,
        currency: value.currency,
        templeId: value.templeId,
        stripeSessionId: value.stripeSessionId,
        amount: value.amount,
        donor: value.donor
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n29(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): DonationStatus {
    return "pending" in value ? DonationStatus.pending : "completed" in value ? DonationStatus.completed : "failed" in value ? DonationStatus.failed : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pooja>): Array<Pooja> {
    return value.map((x)=>from_candid_Pooja_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DarshanTiming>): Array<DarshanTiming> {
    return value.map((x)=>from_candid_DarshanTiming_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Temple>): Array<Temple> {
    return value.map((x)=>from_candid_Temple_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonationRecord>): Array<DonationRecord> {
    return value.map((x)=>from_candid_DonationRecord_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserSummary>): Array<UserSummary> {
    return value.map((x)=>from_candid_UserSummary_n40(_uploadFile, _downloadFile, x));
}
function to_candid_ContactInfo_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactInfo): _ContactInfo {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_DarshanTiming_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DarshanTiming): _DarshanTiming {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Pooja_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Pooja): _Pooja {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_SearchParams_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchParams): _SearchParams {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_TempleInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TempleInput): _TempleInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closeTime: string;
    timingLabel: string;
    breakStart?: string;
    breakEnd?: string;
    openTime: string;
}): {
    closeTime: string;
    timingLabel: string;
    breakStart: [] | [string];
    breakEnd: [] | [string];
    openTime: string;
} {
    return {
        closeTime: value.closeTime,
        timingLabel: value.timingLabel,
        breakStart: value.breakStart ? candid_some(value.breakStart) : candid_none(),
        breakEnd: value.breakEnd ? candid_some(value.breakEnd) : candid_none(),
        openTime: value.openTime
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    poojaSchedule: Array<Pooja>;
    contactInfo: ContactInfo;
    nonHinduRestriction: boolean;
    city: string;
    name: string;
    tags: Array<string>;
    architectureStyle: string;
    description: string;
    history: string;
    district: string;
    donationOptions: Array<DonationOption>;
    state: string;
    averageVisitDuration: bigint;
    address: string;
    specialDarshans: Array<SpecialDarshan>;
    festivalCalendar: Array<Festival>;
    deity: string;
    darshanTimings: Array<DarshanTiming>;
    images: Array<string>;
}): {
    poojaSchedule: Array<_Pooja>;
    contactInfo: _ContactInfo;
    nonHinduRestriction: boolean;
    city: string;
    name: string;
    tags: Array<string>;
    architectureStyle: string;
    description: string;
    history: string;
    district: string;
    donationOptions: Array<_DonationOption>;
    state: string;
    averageVisitDuration: bigint;
    address: string;
    specialDarshans: Array<_SpecialDarshan>;
    festivalCalendar: Array<_Festival>;
    deity: string;
    darshanTimings: Array<_DarshanTiming>;
    images: Array<string>;
} {
    return {
        poojaSchedule: to_candid_vec_n3(_uploadFile, _downloadFile, value.poojaSchedule),
        contactInfo: to_candid_ContactInfo_n6(_uploadFile, _downloadFile, value.contactInfo),
        nonHinduRestriction: value.nonHinduRestriction,
        city: value.city,
        name: value.name,
        tags: value.tags,
        architectureStyle: value.architectureStyle,
        description: value.description,
        history: value.history,
        district: value.district,
        donationOptions: value.donationOptions,
        state: value.state,
        averageVisitDuration: value.averageVisitDuration,
        address: value.address,
        specialDarshans: value.specialDarshans,
        festivalCalendar: value.festivalCalendar,
        deity: value.deity,
        darshanTimings: to_candid_vec_n8(_uploadFile, _downloadFile, value.darshanTimings),
        images: value.images
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitHistory: Array<TempleId>;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    bookmarkedTemples: Array<TempleId>;
}): {
    visitHistory: Array<_TempleId>;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    bookmarkedTemples: Array<_TempleId>;
} {
    return {
        visitHistory: value.visitHistory,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n44(_uploadFile, _downloadFile, value.role),
        email: value.email,
        bookmarkedTemples: value.bookmarkedTemples
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cityFilter?: string;
    pagination: PaginationParams;
    searchTerm: string;
    stateFilter?: string;
}): {
    cityFilter: [] | [string];
    pagination: _PaginationParams;
    searchTerm: string;
    stateFilter: [] | [string];
} {
    return {
        cityFilter: value.cityFilter ? candid_some(value.cityFilter) : candid_none(),
        pagination: value.pagination,
        searchTerm: value.searchTerm,
        stateFilter: value.stateFilter ? candid_some(value.stateFilter) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    time: string;
    description: string;
    price?: bigint;
    isIncluded: boolean;
}): {
    name: string;
    time: string;
    description: string;
    price: [] | [bigint];
    isIncluded: boolean;
} {
    return {
        name: value.name,
        time: value.time,
        description: value.description,
        price: value.price ? candid_some(value.price) : candid_none(),
        isIncluded: value.isIncluded
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email?: string;
    website?: string;
    phone?: string;
}): {
    email: [] | [string];
    website: [] | [string];
    phone: [] | [string];
} {
    return {
        email: value.email ? candid_some(value.email) : candid_none(),
        website: value.website ? candid_some(value.website) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Pooja>): Array<_Pooja> {
    return value.map((x)=>to_candid_Pooja_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DarshanTiming>): Array<_DarshanTiming> {
    return value.map((x)=>to_candid_DarshanTiming_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
